/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import Pack_Jugador.Almacen_de_jugadores;
import Pack_Jugador.Jugador;
import java.awt.Color;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author laura
 */
public class Ranking extends javax.swing.JPanel implements Serializable {

    private StringBuilder texto1 = new StringBuilder();
    private StringBuilder texto2 = new StringBuilder();
    
     private ArrayList<Jugador> ranking_victorias = new ArrayList<Jugador>();
    private ArrayList<Jugador> ranking_nombres = new ArrayList<Jugador>();

    private Almacen_de_jugadores almacenjug;
    private Jugador j2;

    public Ranking(Almacen_de_jugadores almacenj) throws ClassNotFoundException {
        initComponents();
        this.almacenjug = almacenj;
        this.ranking_victorias = almacenjug.ranking_ordenado_por_victorias();
        this.ranking_nombres = almacenjug.ranking_ordenado_por_nombre();
        
        for(Jugador ranking_victorias:this.ranking_victorias){
            texto1 = texto1.append(ranking_victorias.getNombre()).append(" Con un total de: ").append(ranking_victorias.getPartidasGanadas()).append(" Partidas ganadas.\n");
        }
        
        for(Jugador ranking_nombres:this.ranking_nombres){
            texto2 = texto2.append(ranking_nombres.getNombre()).append(" Con un total de: ").append(ranking_nombres.getPartidasGanadas()).append(" Partidas ganadas.\n");
        }
        
        area1.setText(texto1.toString());
        area2.setText(texto2.toString());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        victorias = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        area2 = new javax.swing.JTextArea();
        area1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        victorias.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        victorias.setForeground(new java.awt.Color(0, 0, 0));
        victorias.setText("Ranking por victorias");

        nombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nombre.setForeground(new java.awt.Color(0, 0, 0));
        nombre.setText("Ranking por nombre");

        area2.setColumns(20);
        area2.setRows(5);

        area1.setColumns(20);
        area1.setRows(5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(area1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(area2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(victorias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nombre)
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(victorias)
                    .addComponent(nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(area2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(area1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(134, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area1;
    private javax.swing.JTextArea area2;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel victorias;
    // End of variables declaration//GEN-END:variables
}
